baseurl = "https://www.clouddatascience.org/"
languageCode = "en"
title = "Cloud-Based Data Science"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "Cloud-Based Data Science"
    [[params.navbar.menu]]
      link = "../index.html"
      text = "HOME"
    [[params.navbar.menu]]
      link = "../index.html"
      text = "ABOUT"
    [[params.navbar.menu]]
      link = "./_book/index.html"
      text = "RESOURCES"
    [[params.navbar.menu]]
      link = "https://www.patreon.com/"
      text = "DONATE"
    [[params.navbar.menu]]
      link = "./contact/contact.html"
      text = "CONTACT"

  # Header
  [params.header]
    title = "Cloud-based Data Science"
    text = "Chromebook Data Science (CBDS) is a free, massive open online educational program offered through Leanpub to help anyone who can read, write, and use a computer to move into data science, the number one rated job."
    [params.header.image]
      path = "images/logo-01.png"
      alt = "Watch"
    [params.header.button]
      link = "https://leanpub.com/universities/set/jhu/chromebook-data-science"
      text = "Take our courses today!"

  # Features
  [params.features]
    title = "Our Core Features"
    [params.features.image]
      path = "images/watch-2.png"
      alt = "Watch"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-ion-ios-alarm-outline"
      title = "Smooth Touch"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    [[params.features.left]]
      icon = "tf-ion-ios-bell-outline"
      title = "Elegant Design"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    [[params.features.left]]
      icon = "tf-ion-ios-cart-outline"
      title = "Easy Pricing"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-ios-alarm-outline"
      title = "Smooth Touch"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    [[params.features.right]]
      icon = "tf-ion-ios-bell-outline"
      title = "Elegant Design"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    [[params.features.right]]
      icon = "tf-ion-ios-cart-outline"
      title = "Easy Pricing"
      text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"

  [params.promo]
    title = "Designed by professional , the benefit for creative gigs"
    text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia vel labore, deleniti minima nisi, velit atque quaerat impedit ea maxime sunt accusamus at obcaecati dolor iure iusto omnis quis eum.  \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Quia vel labore, deleniti minima nisi, velit atque quaerat impedit ea maxime sunt accusamus at obcaecati dolor iure iusto omnis quis eum."
    [params.promo.image]
      path = "images/watch.png"
      alt = "Watch"

  [params.feature_list]
    title = "Our Approach"
    [[params.feature_list.items]]
      image = "images/showcase/chromebook.png"
      title = "We minimize computer costs"
      text = "We have developed an online program that lets students do data science using only a web browser and cheap computers like Chromebooks."
      button_link = "https://www.google.com/chromebook/"
      button_text = "Learn more about Google Chromebook"
    [[params.feature_list.items]]
      image = "images/showcase/chromebook.png"
      title = "Free courses"
      text = "Our CBDS program is entirely online and you can take it for free. You can take the classes any time and at your own pace. You get a certificate for each CBDS online class from Leanpub."
      button_link = ""
      button_text = "See our curriculum"
    [[params.feature_list.items]]
      image = "images/showcase/showcase-3.png"
      title = "Learn anywhere"
      text = "Our CBDS program is entirely online and you can take it for free. You can take the classes any time and at your own pace. You get a certificate for each CBDS online class from Leanpub."
      button_link = ""
      button_text = "Learn how"
    [[params.feature_list.items]]
      image = "images/showcase/showcase-3.png"
      title = "Career support"
      text = "Our program covers soft skills you need to get data science jobs, including how to network and get your name out there. We are also interested in working with partner companies who need to fill data science roles to place our graduates in remote and local data science jobs. (If you are looking for data scientists consider becoming a CBDS hiring partner)."
      button_link = ""
      button_text = "Learn how"

  [params.gallery]
    title = "Our Partners"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["partner_hebcac.png", "partner_rstudio.png", "partner_leanpub.png", "partner_datacamp.png", "partner_starbucks.png"]

  [params.call_to_action]
    title = "Stay Connected"
    text = "Enter your email address here to stay connected"
    placeholder = "Your Email Address Here"
    button_text = "Subscribe"

  [params.testimonials]
    title = "Our Team"
    [[params.testimonials.blocks]]
      text = "Jeff Leek is a professor of biostatistics at Johns Hopkins University Bloomberg School of Public Health. He has taught millions of people data science online through massive online open courses. He is also an associate professor at Johns Hopkins Bloomberg School of Public Health and co-director of the Johns Hopkins Data Science Lab."
      name = "Jeffrey Leek"
      position = "Director"
      image = "images/team/Jeff.png"
    [[params.testimonials.blocks]]
      text = "Ashley K.G. Johnson is the program administrator for CBDS+ at the Johns Hopkins Bloomberg School of Public Health. She facilitates tutoring for program participants, manages recruitment efforts and the development of corporate and non-profit partnerships. Ashley is a Baltimore native and a graduate of Loyola University Maryland."
      name = "Ashley Johnson"
      position = "Program Administrator"
      image = "images/team/ashley.png"
    [[params.testimonials.blocks]]
      text = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence."
      name = "Aboozar Hadavand"
      position = "Curriculum Lead"
      image = "images/team/aboozar.jpg"
    [params.testimonials.button]
      link = "./contact/contact.html"
      text = "Contact us if you have any questions"

  # Footer uses navbar data
